# Generated by Django 4.1.7 on 2023-03-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Telegramm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammuser',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
