# Generated by Django 4.1.7 on 2023-03-27 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Telegramm', '0003_remove_telegrammuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammuser',
            name='telelogin',
        ),
        migrations.AddField(
            model_name='telegrammuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegrammuser',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
    ]
