# Generated by Django 4.1.7 on 2023-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('VC', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=4096)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Enter login', max_length=256)),
                ('password', models.CharField(help_text='Enter password', max_length=256)),
            ],
        ),
    ]
