# Generated by Django 4.1.7 on 2023-03-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='PrCom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
        ),
    ]
