# Generated by Django 4.1.7 on 2023-03-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_comment_prcom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product')),
                ('usname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.user')),
            ],
        ),
    ]
