# Generated by Django 4.1.7 on 2023-03-03 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_product_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
        ),
    ]
