# Generated by Django 4.1.7 on 2023-03-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_comment_pruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='usname',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
