# Generated by Django 4.1.7 on 2023-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(max_length=129, null=True),
        ),
    ]
